language: python
python:
        - "3.6"

    services:
        - docker

    bedore_script:  pip install docker-compose

    script:
        - docker-compose run app sh -c "python manage.py tst && flake8"